server.port: 8090

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://localhost:8080/.well-known/jwks.json

showcase:
  jwt: false
  jpa: false
  introspection:
    edpoint: https://localhost:8080/introspect
    client-id: showcase-resource-server
    password: secret

---
spring.profiles: jwt
showcase:
  jwt: true

---
spring.profiles: jpa
showcase:
  jpa: true